### ISSUE TITLE
Enhancement of daily codes

### ISSUE THREAD

**Issue by sjnoone** [glamod/glamod-nuim#24]
I have enhanced bit of all the 3 daily codes and the utils.py files.

**Comment by rjhd2** [comment]
PR #25 includes files from closed issue #20 in the commit.  Maybe branched of branch. 

This branch `20_daily_code_enhancement` correctly only has changes to the 3 daily files and `utils`.

Intended solution

- retain changed files (daily ones) locallly (in a temporary directory) just to be sure. 
- check out master and update (git pull)
- check out this branch and update (git checkout 20_daily....  ; git pull).  Should have edits from #7/#23 in it
- make sure the edited files are still correct
- make a new pull request and see if that's only got the single commit in it, continue from there.
- close original pull request with a note to explain
