### ISSUE TITLE
Daily csv to CDM format issues with code

### ISSUE THREAD

**Issue by sjnoone** [glamod/glamod-nuim#42]
1) Code crashed on file with only two lines of data e.g :MUM00041241.csv.gz. code will not read in TMIN in this file first line, this file crashed the cdmlite and cdmobs code.
It is because we haven't included "header=none" in the read.csv line.Therefore the first line of the csv data files (first timestamp) has been lost on this run so need to fix and re-run again
2) Issue with daily_to_obs_table_v1.py in line 312  should be `df["observation_id"] = df["observation_id"] + '-' + df['observed_variable'] + '-' + df['value_significance']`
to include `+ '-'` after `df['observed_variable']`.
3) Code does not sort the files by timestamps.
4) Code does not recognise if files have already been CDM processed and overwrites them and does not skip; `--clobber` not working on JASMIN for cdmlite or cdmobs daily.
5) It took approx 14 hours to run daily cdmlite and cdmobs simultanously from start to finish and then the cdmhead files took approx 12 hours

**Comment by sjnoone** [comment]
Ok Im not sure why it didnt work for me , I used: python daily_to_cdm_lite_v1.py --subset ls_1.txt --clobber but it just started processing form the begginining of the list again. Whta is the renaming issue?

**Comment by rjhd2** [comment]
Using the `--clobber` will always result in files being overwritten.  Leaving this argument out means that existing files will be skipped
