### ISSUE TITLE
Code to extract station configuration information from final outputted tables.

### ISSUE THREAD

**Issue by sjnoone** [glamod/glamod-nuim#46]
We need to collate a station inventory of all processed files (sbdy,dy,mthly) showing the primary_id, secondary_id,  record_number, station_name, start_year, end_year, observed_variables, for each station. I need this information to finalise the station_configuration_file.

**Comment by rjhd2** [comment]
Read CDM Lite tables after all have been produced to pull out the information rather than gathering on the fly.

**Comment by rjhd2** [comment]
Daily and Monthly works OK too.

**Comment by sjnoone** [comment]
thats great , thanks.
