### ISSUE TITLE
station_config extract code for daily issue

### ISSUE THREAD

**Issue by sjnoone** [glamod/glamod-nuim#57]
I ran the extract_station_config_info.py code on the daily CDM_lite output files  but it has not compiled information for quite a few stations (see attached file). I have checked a couple of the output files an data exists e.g. cdm_lite_r202208_USS0015J15S.psv.gz so the problem is in the code.

**Comment by rjhd2** [comment]
USS0015J15S is in the file you sent me:
`USS0015J15S|1|NV Hole-in-Mountain|1981|2022|[55, 44, 85, 53]`
Will chat to determine details of what's not in the files (I don't know what to expect for specific example)

**Comment by sjnoone** [comment]
its ok sorry the file did'nt speartor properly and some values were lost! Everything is fine with the file now.

**Comment by sjnoone** [comment]
raised in error now sorted
