### ISSUE TITLE
Rel7: update to using CDM Core format

### ISSUE THREAD

**Issue by rjhd2** [glamod/glamod-nuim#91]
Update conversion code to use CDM Core format

**Comment by rjhd2** [comment]
Will need to update configuration file with these extra entries for the CDM Core:

```
subdaily_cdmcore_outdir
subdaily_cdmcore_file
subdaily_station_records_obs_core
```

**Comment by sjnoone** [comment]
All these edits look good and ran code locally as a check and worked perfectly. thanks ! Simon
